/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const NoteId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AIAnalysisResult = IDL.Record({
  'flags' : IDL.Vec(IDL.Text),
  'noteId' : NoteId,
  'suggestedTitle' : IDL.Text,
  'similarityPercent' : IDL.Opt(IDL.Nat),
  'score' : IDL.Nat,
  'suggestedTags' : IDL.Vec(IDL.Text),
  'similarNoteId' : IDL.Opt(NoteId),
  'timestamp' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AILogEntry = IDL.Record({
  'flags' : IDL.Vec(IDL.Text),
  'noteId' : NoteId,
  'similarityPercent' : IDL.Opt(IDL.Nat),
  'score' : IDL.Nat,
  'similarNoteId' : IDL.Opt(NoteId),
  'timestamp' : Timestamp,
});
export const TopContributor = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'totalEarned' : IDL.Nat,
  'avgAIScore' : IDL.Opt(IDL.Nat),
  'totalUploads' : IDL.Nat,
});
export const SubjectDownloadStat = IDL.Record({
  'subject' : IDL.Text,
  'downloadCount' : IDL.Nat,
});
export const WeeklyUploadPoint = IDL.Record({
  'count' : IDL.Nat,
  'weekLabel' : IDL.Text,
});
export const AnalyticsData = IDL.Record({
  'topContributors' : IDL.Vec(TopContributor),
  'removedNotes' : IDL.Nat,
  'downloadsPerSubject' : IDL.Vec(SubjectDownloadStat),
  'totalCreditsAwarded' : IDL.Nat,
  'totalNotes' : IDL.Nat,
  'weeklyUploads' : IDL.Vec(WeeklyUploadPoint),
  'totalUsers' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
  'flaggedNotes' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'credits' : IDL.Nat,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'totalEarned' : IDL.Nat,
  'totalUploads' : IDL.Nat,
});
export const ModerationItem = IDL.Record({
  'noteId' : NoteId,
  'flagReason' : IDL.Text,
  'noteTitle' : IDL.Text,
  'aiFlags' : IDL.Vec(IDL.Text),
  'uploaderPrincipal' : UserId,
  'flaggedAt' : Timestamp,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'creditsAwarded' : IDL.Nat,
  'title' : IDL.Text,
  'uploaderName' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'qualityStars' : IDL.Nat,
  'uploaderPrincipal' : UserId,
  'timestamp' : Timestamp,
  'downloadCount' : IDL.Nat,
  'price' : IDL.Nat,
  'aiScore' : IDL.Opt(IDL.Nat),
  'isFlagged' : IDL.Bool,
  'isRemoved' : IDL.Bool,
  'fileRef' : IDL.Text,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'banned' : IDL.Record({
    'adminPrincipal' : UserId,
    'timestamp' : Timestamp,
    'reason' : IDL.Text,
  }),
  'suspended' : IDL.Record({
    'until' : IDL.Opt(Timestamp),
    'reason' : IDL.Text,
  }),
});
export const UserAdminView = IDL.Record({
  'status' : AccountStatus,
  'principal' : UserId,
  'credits' : IDL.Nat,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'totalEarned' : IDL.Nat,
  'totalUploads' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'uploaderName' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'fileRef' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCredits' : IDL.Func([UserId, IDL.Nat], [], []),
  'analyzeNoteQuality' : IDL.Func([NoteId], [AIAnalysisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([UserId, IDL.Text], [], []),
  'downloadNote' : IDL.Func([NoteId], [], []),
  'flagNote' : IDL.Func([NoteId, IDL.Text], [], []),
  'getAIAnalysisResult' : IDL.Func(
      [NoteId],
      [IDL.Opt(AIAnalysisResult)],
      ['query'],
    ),
  'getAILogs' : IDL.Func([], [IDL.Vec(AILogEntry)], ['query']),
  'getAdminAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getModerationQueue' : IDL.Func([], [IDL.Vec(ModerationItem)], ['query']),
  'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getOpenAIKey' : IDL.Func([], [IDL.Bool], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCreditsAwarded' : IDL.Nat,
          'totalDownloads' : IDL.Nat,
          'totalUploads' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRecentUploads' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'getUserList' : IDL.Func([], [IDL.Vec(UserAdminView)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeNote' : IDL.Func([NoteId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'suspendUser' : IDL.Func([UserId, IDL.Text, IDL.Opt(Timestamp)], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsuspendUser' : IDL.Func([UserId], [], []),
  'updateQuality' : IDL.Func([NoteId, IDL.Nat], [], []),
  'uploadNoteWithFile' : IDL.Func([NoteInput], [NoteId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const NoteId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AIAnalysisResult = IDL.Record({
    'flags' : IDL.Vec(IDL.Text),
    'noteId' : NoteId,
    'suggestedTitle' : IDL.Text,
    'similarityPercent' : IDL.Opt(IDL.Nat),
    'score' : IDL.Nat,
    'suggestedTags' : IDL.Vec(IDL.Text),
    'similarNoteId' : IDL.Opt(NoteId),
    'timestamp' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AILogEntry = IDL.Record({
    'flags' : IDL.Vec(IDL.Text),
    'noteId' : NoteId,
    'similarityPercent' : IDL.Opt(IDL.Nat),
    'score' : IDL.Nat,
    'similarNoteId' : IDL.Opt(NoteId),
    'timestamp' : Timestamp,
  });
  const TopContributor = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'totalEarned' : IDL.Nat,
    'avgAIScore' : IDL.Opt(IDL.Nat),
    'totalUploads' : IDL.Nat,
  });
  const SubjectDownloadStat = IDL.Record({
    'subject' : IDL.Text,
    'downloadCount' : IDL.Nat,
  });
  const WeeklyUploadPoint = IDL.Record({
    'count' : IDL.Nat,
    'weekLabel' : IDL.Text,
  });
  const AnalyticsData = IDL.Record({
    'topContributors' : IDL.Vec(TopContributor),
    'removedNotes' : IDL.Nat,
    'downloadsPerSubject' : IDL.Vec(SubjectDownloadStat),
    'totalCreditsAwarded' : IDL.Nat,
    'totalNotes' : IDL.Nat,
    'weeklyUploads' : IDL.Vec(WeeklyUploadPoint),
    'totalUsers' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
    'flaggedNotes' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'credits' : IDL.Nat,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'totalEarned' : IDL.Nat,
    'totalUploads' : IDL.Nat,
  });
  const ModerationItem = IDL.Record({
    'noteId' : NoteId,
    'flagReason' : IDL.Text,
    'noteTitle' : IDL.Text,
    'aiFlags' : IDL.Vec(IDL.Text),
    'uploaderPrincipal' : UserId,
    'flaggedAt' : Timestamp,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'creditsAwarded' : IDL.Nat,
    'title' : IDL.Text,
    'uploaderName' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'qualityStars' : IDL.Nat,
    'uploaderPrincipal' : UserId,
    'timestamp' : Timestamp,
    'downloadCount' : IDL.Nat,
    'price' : IDL.Nat,
    'aiScore' : IDL.Opt(IDL.Nat),
    'isFlagged' : IDL.Bool,
    'isRemoved' : IDL.Bool,
    'fileRef' : IDL.Text,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Record({
      'adminPrincipal' : UserId,
      'timestamp' : Timestamp,
      'reason' : IDL.Text,
    }),
    'suspended' : IDL.Record({
      'until' : IDL.Opt(Timestamp),
      'reason' : IDL.Text,
    }),
  });
  const UserAdminView = IDL.Record({
    'status' : AccountStatus,
    'principal' : UserId,
    'credits' : IDL.Nat,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'totalEarned' : IDL.Nat,
    'totalUploads' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'uploaderName' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'fileRef' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCredits' : IDL.Func([UserId, IDL.Nat], [], []),
    'analyzeNoteQuality' : IDL.Func([NoteId], [AIAnalysisResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([UserId, IDL.Text], [], []),
    'downloadNote' : IDL.Func([NoteId], [], []),
    'flagNote' : IDL.Func([NoteId, IDL.Text], [], []),
    'getAIAnalysisResult' : IDL.Func(
        [NoteId],
        [IDL.Opt(AIAnalysisResult)],
        ['query'],
      ),
    'getAILogs' : IDL.Func([], [IDL.Vec(AILogEntry)], ['query']),
    'getAdminAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getModerationQueue' : IDL.Func([], [IDL.Vec(ModerationItem)], ['query']),
    'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getOpenAIKey' : IDL.Func([], [IDL.Bool], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCreditsAwarded' : IDL.Nat,
            'totalDownloads' : IDL.Nat,
            'totalUploads' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRecentUploads' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'getUserList' : IDL.Func([], [IDL.Vec(UserAdminView)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeNote' : IDL.Func([NoteId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'suspendUser' : IDL.Func([UserId, IDL.Text, IDL.Opt(Timestamp)], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsuspendUser' : IDL.Func([UserId], [], []),
    'updateQuality' : IDL.Func([NoteId, IDL.Nat], [], []),
    'uploadNoteWithFile' : IDL.Func([NoteInput], [NoteId], []),
  });
};

export const init = ({ IDL }) => { return []; };