/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAnalysisResult {
  'flags' : Array<string>,
  'noteId' : NoteId,
  'suggestedTitle' : string,
  'similarityPercent' : [] | [bigint],
  'score' : bigint,
  'suggestedTags' : Array<string>,
  'similarNoteId' : [] | [NoteId],
  'timestamp' : Timestamp,
}
export interface AILogEntry {
  'flags' : Array<string>,
  'noteId' : NoteId,
  'similarityPercent' : [] | [bigint],
  'score' : bigint,
  'similarNoteId' : [] | [NoteId],
  'timestamp' : Timestamp,
}
export type AccountStatus = { 'active' : null } |
  {
    'banned' : {
      'adminPrincipal' : UserId,
      'timestamp' : Timestamp,
      'reason' : string,
    }
  } |
  { 'suspended' : { 'until' : [] | [Timestamp], 'reason' : string } };
export interface AnalyticsData {
  'topContributors' : Array<TopContributor>,
  'removedNotes' : bigint,
  'downloadsPerSubject' : Array<SubjectDownloadStat>,
  'totalCreditsAwarded' : bigint,
  'totalNotes' : bigint,
  'weeklyUploads' : Array<WeeklyUploadPoint>,
  'totalUsers' : bigint,
  'totalDownloads' : bigint,
  'flaggedNotes' : bigint,
}
export interface ModerationItem {
  'noteId' : NoteId,
  'flagReason' : string,
  'noteTitle' : string,
  'aiFlags' : Array<string>,
  'uploaderPrincipal' : UserId,
  'flaggedAt' : Timestamp,
}
export interface Note {
  'id' : NoteId,
  'creditsAwarded' : bigint,
  'title' : string,
  'uploaderName' : string,
  'subject' : string,
  'description' : string,
  'qualityStars' : bigint,
  'uploaderPrincipal' : UserId,
  'timestamp' : Timestamp,
  'downloadCount' : bigint,
  'price' : bigint,
  'aiScore' : [] | [bigint],
  'isFlagged' : boolean,
  'isRemoved' : boolean,
  'fileRef' : string,
}
export type NoteId = bigint;
export interface NoteInput {
  'title' : string,
  'uploaderName' : string,
  'subject' : string,
  'description' : string,
  'price' : bigint,
  'fileRef' : string,
}
export interface SubjectDownloadStat {
  'subject' : string,
  'downloadCount' : bigint,
}
export type Timestamp = bigint;
export interface TopContributor {
  'principal' : UserId,
  'name' : string,
  'totalEarned' : bigint,
  'avgAIScore' : [] | [bigint],
  'totalUploads' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserAdminView {
  'status' : AccountStatus,
  'principal' : UserId,
  'credits' : bigint,
  'name' : string,
  'joinedAt' : Timestamp,
  'totalEarned' : bigint,
  'totalUploads' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'credits' : bigint,
  'name' : string,
  'joinedAt' : Timestamp,
  'totalEarned' : bigint,
  'totalUploads' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyUploadPoint { 'count' : bigint, 'weekLabel' : string }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCredits' : ActorMethod<[UserId, bigint], undefined>,
  'analyzeNoteQuality' : ActorMethod<[NoteId], AIAnalysisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[UserId, string], undefined>,
  'downloadNote' : ActorMethod<[NoteId], undefined>,
  'flagNote' : ActorMethod<[NoteId, string], undefined>,
  'getAIAnalysisResult' : ActorMethod<[NoteId], [] | [AIAnalysisResult]>,
  'getAILogs' : ActorMethod<[], Array<AILogEntry>>,
  'getAdminAnalytics' : ActorMethod<[], AnalyticsData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getModerationQueue' : ActorMethod<[], Array<ModerationItem>>,
  'getMyCredits' : ActorMethod<[], bigint>,
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getOpenAIKey' : ActorMethod<[], boolean>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'totalCreditsAwarded' : bigint,
      'totalDownloads' : bigint,
      'totalUploads' : bigint,
    }
  >,
  'getRecentUploads' : ActorMethod<[bigint], Array<Note>>,
  'getUserList' : ActorMethod<[], Array<UserAdminView>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeNote' : ActorMethod<[NoteId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'suspendUser' : ActorMethod<[UserId, string, [] | [Timestamp]], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsuspendUser' : ActorMethod<[UserId], undefined>,
  'updateQuality' : ActorMethod<[NoteId, bigint], undefined>,
  'uploadNoteWithFile' : ActorMethod<[NoteInput], NoteId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];