/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Note {
    id: NoteId;
    creditsAwarded: bigint;
    title: string;
    uploaderName: string;
    subject: string;
    description: string;
    qualityStars: bigint;
    uploaderPrincipal: UserId;
    timestamp: Timestamp;
    downloadCount: bigint;
    price: bigint;
    aiScore?: bigint;
    isFlagged: boolean;
    isRemoved: boolean;
    fileRef: string;
}
export type NoteId = bigint;
export interface UserAdminView {
    status: AccountStatus;
    principal: UserId;
    credits: bigint;
    name: string;
    joinedAt: Timestamp;
    totalEarned: bigint;
    totalUploads: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TopContributor {
    principal: UserId;
    name: string;
    totalEarned: bigint;
    avgAIScore?: bigint;
    totalUploads: bigint;
}
export type Timestamp = bigint;
export interface ModerationItem {
    noteId: NoteId;
    flagReason: string;
    noteTitle: string;
    aiFlags: Array<string>;
    uploaderPrincipal: UserId;
    flaggedAt: Timestamp;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AnalyticsData {
    topContributors: Array<TopContributor>;
    removedNotes: bigint;
    downloadsPerSubject: Array<SubjectDownloadStat>;
    totalCreditsAwarded: bigint;
    totalNotes: bigint;
    weeklyUploads: Array<WeeklyUploadPoint>;
    totalUsers: bigint;
    totalDownloads: bigint;
    flaggedNotes: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface AIAnalysisResult {
    flags: Array<string>;
    noteId: NoteId;
    suggestedTitle: string;
    similarityPercent?: bigint;
    score: bigint;
    suggestedTags: Array<string>;
    similarNoteId?: NoteId;
    timestamp: Timestamp;
}
export interface NoteInput {
    title: string;
    uploaderName: string;
    subject: string;
    description: string;
    price: bigint;
    fileRef: string;
}
export type AccountStatus = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "banned";
    banned: {
        adminPrincipal: UserId;
        timestamp: Timestamp;
        reason: string;
    };
} | {
    __kind__: "suspended";
    suspended: {
        until?: Timestamp;
        reason: string;
    };
};
export interface AILogEntry {
    flags: Array<string>;
    noteId: NoteId;
    similarityPercent?: bigint;
    score: bigint;
    similarNoteId?: NoteId;
    timestamp: Timestamp;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface WeeklyUploadPoint {
    count: bigint;
    weekLabel: string;
}
export interface UserProfile {
    principal: UserId;
    credits: bigint;
    name: string;
    joinedAt: Timestamp;
    totalEarned: bigint;
    totalUploads: bigint;
}
export interface SubjectDownloadStat {
    subject: string;
    downloadCount: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCredits(user: UserId, amount: bigint): Promise<void>;
    analyzeNoteQuality(noteId: NoteId): Promise<AIAnalysisResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(target: UserId, reason: string): Promise<void>;
    downloadNote(noteId: NoteId): Promise<void>;
    flagNote(noteId: NoteId, reason: string): Promise<void>;
    getAIAnalysisResult(noteId: NoteId): Promise<AIAnalysisResult | null>;
    getAILogs(): Promise<Array<AILogEntry>>;
    getAdminAnalytics(): Promise<AnalyticsData>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(): Promise<Array<UserProfile>>;
    getModerationQueue(): Promise<Array<ModerationItem>>;
    getMyCredits(): Promise<bigint>;
    getNote(noteId: NoteId): Promise<Note | null>;
    getNotes(): Promise<Array<Note>>;
    getOpenAIKey(): Promise<boolean>;
    getPlatformStats(): Promise<{
        totalCreditsAwarded: bigint;
        totalDownloads: bigint;
        totalUploads: bigint;
    }>;
    getRecentUploads(limit: bigint): Promise<Array<Note>>;
    getUserList(): Promise<Array<UserAdminView>>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeNote(noteId: NoteId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setOpenAIKey(key: string): Promise<void>;
    suspendUser(target: UserId, reason: string, until: Timestamp | null): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unsuspendUser(target: UserId): Promise<void>;
    updateQuality(noteId: NoteId, stars: bigint): Promise<void>;
    uploadNoteWithFile(input: NoteInput): Promise<NoteId>;
}
import type { AIAnalysisResult as _AIAnalysisResult, AILogEntry as _AILogEntry, AccountStatus as _AccountStatus, AnalyticsData as _AnalyticsData, Note as _Note, NoteId as _NoteId, SubjectDownloadStat as _SubjectDownloadStat, Timestamp as _Timestamp, TopContributor as _TopContributor, UserAdminView as _UserAdminView, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, WeeklyUploadPoint as _WeeklyUploadPoint, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCredits(arg0: UserId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0, arg1);
            return result;
        }
    }
    async analyzeNoteQuality(arg0: NoteId): Promise<AIAnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeNoteQuality(arg0);
                return from_candid_AIAnalysisResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeNoteQuality(arg0);
            return from_candid_AIAnalysisResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: UserId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0, arg1);
            return result;
        }
    }
    async downloadNote(arg0: NoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadNote(arg0);
            return result;
        }
    }
    async flagNote(arg0: NoteId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagNote(arg0, arg1);
            return result;
        }
    }
    async getAIAnalysisResult(arg0: NoteId): Promise<AIAnalysisResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIAnalysisResult(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIAnalysisResult(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAILogs(): Promise<Array<AILogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAILogs();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAILogs();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminAnalytics(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return from_candid_AnalyticsData_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return from_candid_AnalyticsData_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getModerationQueue(): Promise<Array<ModerationItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModerationQueue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModerationQueue();
            return result;
        }
    }
    async getMyCredits(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCredits();
            return result;
        }
    }
    async getNote(arg0: NoteId): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenAIKey(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenAIKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenAIKey();
            return result;
        }
    }
    async getPlatformStats(): Promise<{
        totalCreditsAwarded: bigint;
        totalDownloads: bigint;
        totalUploads: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getRecentUploads(arg0: bigint): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentUploads(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentUploads(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserList(): Promise<Array<UserAdminView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserList();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserList();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeNote(arg0: NoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNote(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async suspendUser(arg0: UserId, arg1: string, arg2: Timestamp | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unsuspendUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendUser(arg0);
            return result;
        }
    }
    async updateQuality(arg0: NoteId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuality(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuality(arg0, arg1);
            return result;
        }
    }
    async uploadNoteWithFile(arg0: NoteInput): Promise<NoteId> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadNoteWithFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadNoteWithFile(arg0);
            return result;
        }
    }
}
function from_candid_AIAnalysisResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIAnalysisResult): AIAnalysisResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AILogEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AILogEntry): AILogEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AccountStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsData): AnalyticsData {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TopContributor_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopContributor): TopContributor {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserAdminView_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAdminView): UserAdminView {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NoteId]): NoteId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIAnalysisResult]): AIAnalysisResult | null {
    return value.length === 0 ? null : from_candid_AIAnalysisResult_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flags: Array<string>;
    noteId: _NoteId;
    similarityPercent: [] | [bigint];
    score: bigint;
    similarNoteId: [] | [_NoteId];
    timestamp: _Timestamp;
}): {
    flags: Array<string>;
    noteId: NoteId;
    similarityPercent?: bigint;
    score: bigint;
    similarNoteId?: NoteId;
    timestamp: Timestamp;
} {
    return {
        flags: value.flags,
        noteId: value.noteId,
        similarityPercent: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.similarityPercent)),
        score: value.score,
        similarNoteId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.similarNoteId)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topContributors: Array<_TopContributor>;
    removedNotes: bigint;
    downloadsPerSubject: Array<_SubjectDownloadStat>;
    totalCreditsAwarded: bigint;
    totalNotes: bigint;
    weeklyUploads: Array<_WeeklyUploadPoint>;
    totalUsers: bigint;
    totalDownloads: bigint;
    flaggedNotes: bigint;
}): {
    topContributors: Array<TopContributor>;
    removedNotes: bigint;
    downloadsPerSubject: Array<SubjectDownloadStat>;
    totalCreditsAwarded: bigint;
    totalNotes: bigint;
    weeklyUploads: Array<WeeklyUploadPoint>;
    totalUsers: bigint;
    totalDownloads: bigint;
    flaggedNotes: bigint;
} {
    return {
        topContributors: from_candid_vec_n19(_uploadFile, _downloadFile, value.topContributors),
        removedNotes: value.removedNotes,
        downloadsPerSubject: value.downloadsPerSubject,
        totalCreditsAwarded: value.totalCreditsAwarded,
        totalNotes: value.totalNotes,
        weeklyUploads: value.weeklyUploads,
        totalUsers: value.totalUsers,
        totalDownloads: value.totalDownloads,
        flaggedNotes: value.flaggedNotes
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    totalEarned: bigint;
    avgAIScore: [] | [bigint];
    totalUploads: bigint;
}): {
    principal: UserId;
    name: string;
    totalEarned: bigint;
    avgAIScore?: bigint;
    totalUploads: bigint;
} {
    return {
        principal: value.principal,
        name: value.name,
        totalEarned: value.totalEarned,
        avgAIScore: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avgAIScore)),
        totalUploads: value.totalUploads
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    creditsAwarded: bigint;
    title: string;
    uploaderName: string;
    subject: string;
    description: string;
    qualityStars: bigint;
    uploaderPrincipal: _UserId;
    timestamp: _Timestamp;
    downloadCount: bigint;
    price: bigint;
    aiScore: [] | [bigint];
    isFlagged: boolean;
    isRemoved: boolean;
    fileRef: string;
}): {
    id: NoteId;
    creditsAwarded: bigint;
    title: string;
    uploaderName: string;
    subject: string;
    description: string;
    qualityStars: bigint;
    uploaderPrincipal: UserId;
    timestamp: Timestamp;
    downloadCount: bigint;
    price: bigint;
    aiScore?: bigint;
    isFlagged: boolean;
    isRemoved: boolean;
    fileRef: string;
} {
    return {
        id: value.id,
        creditsAwarded: value.creditsAwarded,
        title: value.title,
        uploaderName: value.uploaderName,
        subject: value.subject,
        description: value.description,
        qualityStars: value.qualityStars,
        uploaderPrincipal: value.uploaderPrincipal,
        timestamp: value.timestamp,
        downloadCount: value.downloadCount,
        price: value.price,
        aiScore: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.aiScore)),
        isFlagged: value.isFlagged,
        isRemoved: value.isRemoved,
        fileRef: value.fileRef
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AccountStatus;
    principal: _UserId;
    credits: bigint;
    name: string;
    joinedAt: _Timestamp;
    totalEarned: bigint;
    totalUploads: bigint;
}): {
    status: AccountStatus;
    principal: UserId;
    credits: bigint;
    name: string;
    joinedAt: Timestamp;
    totalEarned: bigint;
    totalUploads: bigint;
} {
    return {
        status: from_candid_AccountStatus_n32(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        credits: value.credits,
        name: value.name,
        joinedAt: value.joinedAt,
        totalEarned: value.totalEarned,
        totalUploads: value.totalUploads
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    until: [] | [_Timestamp];
    reason: string;
}): {
    until?: Timestamp;
    reason: string;
} {
    return {
        until: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.until)),
        reason: value.reason
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flags: Array<string>;
    noteId: _NoteId;
    suggestedTitle: string;
    similarityPercent: [] | [bigint];
    score: bigint;
    suggestedTags: Array<string>;
    similarNoteId: [] | [_NoteId];
    timestamp: _Timestamp;
}): {
    flags: Array<string>;
    noteId: NoteId;
    suggestedTitle: string;
    similarityPercent?: bigint;
    score: bigint;
    suggestedTags: Array<string>;
    similarNoteId?: NoteId;
    timestamp: Timestamp;
} {
    return {
        flags: value.flags,
        noteId: value.noteId,
        suggestedTitle: value.suggestedTitle,
        similarityPercent: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.similarityPercent)),
        score: value.score,
        suggestedTags: value.suggestedTags,
        similarNoteId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.similarNoteId)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    banned: {
        adminPrincipal: _UserId;
        timestamp: _Timestamp;
        reason: string;
    };
} | {
    suspended: {
        until: [] | [_Timestamp];
        reason: string;
    };
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "banned";
    banned: {
        adminPrincipal: UserId;
        timestamp: Timestamp;
        reason: string;
    };
} | {
    __kind__: "suspended";
    suspended: {
        until?: Timestamp;
        reason: string;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "banned" in value ? {
        __kind__: "banned",
        banned: value.banned
    } : "suspended" in value ? {
        __kind__: "suspended",
        suspended: from_candid_record_n34(_uploadFile, _downloadFile, value.suspended)
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AILogEntry>): Array<AILogEntry> {
    return value.map((x)=>from_candid_AILogEntry_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopContributor>): Array<TopContributor> {
    return value.map((x)=>from_candid_TopContributor_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAdminView>): Array<UserAdminView> {
    return value.map((x)=>from_candid_UserAdminView_n30(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
